language: node_js
os: linux
node_js:
  - '8'
before_deploy:
  - yarn build
deploy:
  - provider: pages
    cleanup: false
    token: $GITHUB_PAGES_TOKEN
    local_dir: ./release
    email: 'integrations@ringcentral.com'
    name: 'RingCentral Integrations Team'
    on:
      branch: master
