# Project information
site_name: RingCentral Embeddable
site_url: https://ringcentral.github.io/ringcentral-embeddable/docs

# Repository
repo_url: https://github.com/ringcentral/ringcentral-embeddable
repo_name: ringcentral/ringcentral-embeddable
edit_uri: tree/main/docs
docs_dir: docs

theme:
  name: material
  features:
      - navigation.path
#      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.expand
      - navigation.sections
      - search.sharing
      - search.highlight
      - content.code.copy
      - content.action.edit
      - content.action.view
      - content.code.annotate

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - exclude:
      regex:
        - '^\.#.*'

extra_css:
  - extra.css

extra_javascript:
  - extra.js

markdown_extensions:
  - attr_list
  - md_in_html
  - mdx_include
  - admonition
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: "2023 RingCentral, Inc. All rights reserved."

nav:
- 'Home': https://ringcentral.github.io/ringcentral-embeddable/

- 'Getting started':
  - 'Registering your application': app-registration.md
  - 'Develop and graduate your app': app-development.md
  - 'Initialization':
     - 'Javascript vs iframes': initialization.md
     - 'Version control': versions.md
     - 'Self-hosting': self-hosting.md

- 'Configuration':
  - 'All parameters': config/index.md
  - 'Setting parameters': config/setting-params.md
  - 'Advanced parameters':
    - 'Custom X-User-Agent': config/user-agent.md
    - 'Custom Client ID': config/client-id.md
    - 'Custom styles through CSS': config/styles.md
    - 'Custom redirect Uri': config/redirect-uri.md
    - 'Custom prefix': config/prefix.md
    - 'Default call settings': config/call-settings.md
    - 'Multiple Partner Brand Support': multiple-brands.md
    - 'Opening in a separate window': config/popup-window.md
    - 'Running in multiple tabs': config/multiple-tabs.md
    - 'Setting your environment': config/environment.md
    - 'Quick access badge': config/badge.md

- 'Developer guide':
  - 'Events': integration/events.md
  - 'API': integration/api.md
  - 'Authorization': integration/authorization.md
  - 'Service features':
    - 'Service registration': integration/index.md
    - 'Address book integration': integration/address-book.md
    - 'Contact activities': integration/contact-activities.md
    - 'Custom settings': integration/custom-settings.md
    - 'Feedback prompt': integration/feedback-prompt.md
    - 'Log calls': integration/call-logging.md
    - 'Log meetings': integration/log-video-meeting.md
    - 'Log messages': integration/message-logging.md
    - 'Schedule meetings': integration/meeting-schedule.md
    - 'Third-party auth': integration/third-party-auth.md
    - 'View upcoming meetings': integration/upcoming-meetings.md
    - 'VCard click handling': integration/vcard-clicks.md
    - 'SMS toolbar button': 'integration/sms-toolbar-button.md'
  - 'Recipes':
    - 'Analytics integration': integration/analytics.md
    - 'Click-to-dial enablement': integration/click-to-dial.md

- 'Troubleshooting': support.md

- 'Changelog': https://github.com/ringcentral/ringcentral-embeddable/releases
