name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
        env:
          TEST_HEADLESS: true
          TEST_HOST_URI: http://localhost:8080
          TEST_JWT_TOKEN: ${{ secrets.TEST_JWT_TOKEN }}
          TEST_THIRD_PARTY_URI: https://ringcentral-tutorials.github.io/ringcentral-embeddable-demos/
          API_KEY: ${{ secrets.TEST_API_KEY }}
          API_SECRET: ${{ secrets.TEST_API_SECRET }}
          API_SERVER: ${{ secrets.API_SERVER }}
  build:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SERVER: ${{ secrets.API_SERVER }}
          HOSTING_URL: ${{ secrets.HOSTING_URL }}
          SEGMENT_KEY: ${{ secrets.SEGMENT_KEY }}
          ANALYTICS_SECRET_KEY: ${{ secrets.ANALYTICS_SECRET_KEY }}
      - run: ./build_brand_themes.sh
      - name: Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
          CLEAN: true
  extension-build:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn build-extension
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SERVER: ${{ secrets.API_SERVER }}
          SEGMENT_KEY: ${{ secrets.SEGMENT_KEY }}
          ANALYTICS_SECRET_KEY: ${{ secrets.ANALYTICS_SECRET_KEY }}
      - run: ./build_brand_themes.sh
      - name: Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: extension-build
          FOLDER: extension
          CLEAN: true
